apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lab-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: metallb
            path: infrastructure/metallb
            namespace: metallb-system
          - name: cert-manager
            path: infrastructure/cert-manager
            namespace: cert-manager
          - name: traefik
            path: infrastructure/traefik
            namespace: traefik
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/rerichardjr/flux-av.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true



