apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: metallb
            namespace: metallb-system
            repoURL: https://metallb.github.io/metallb
            chart: metallb
            targetRevision: 0.15.2
          - name: cert-manager
            namespace: cert-manager
            repoURL: https://charts.jetstack.io
            chart: cert-manager
            targetRevision: v1.18.2
          - name: traefik
            namespace: traefik
            repoURL: https://traefik.github.io/charts
            chart: traefik
            targetRevision: 37.0.0
          - name: grafana
            namespace: monitoring
            repoURL: https://grafana.github.io/helm-charts
            chart: grafana
            targetRevision: 9.4.4
          - name: prometheus
            namespace: monitoring
            repoURL: https://prometheus-community.github.io/helm-charts
            chart: prometheus
            targetRevision: 27.35.0
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: default
      source:
        repoURL: '{{.repoURL}}'
        chart: '{{.chart}}'
        targetRevision: '{{.targetRevision}}'
        helm: {}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{- if eq .name "cert-manager" }}
    spec:
      source:
        helm:
          values: |
            installCRDs: true
    {{- end }}
    {{- if eq .name "grafana" }}
    spec:
      source:
        helm:
          values: |
            datasources:
              datasources.yaml:
                apiVersion: 1
                datasources:
                  - name: Prometheus
                    type: prometheus
                    url: http://prometheus-server.monitoring.svc.cluster.local
                    access: proxy
                    isDefault: true
    {{- end }}




