apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 27.0.2
    helm:
      values: |
        ingressClass:
          enabled: true
          isDefaultClass: true
          name: traefik
        service:
          type: LoadBalancer
        rbac:
          enabled: true
        crds:
          enabled: true
        additionalArguments:
          - "--providers.kubernetescrd.allowCrossNamespace=true"
          - "--entrypoints.web.address=:80"
          - "--entrypoints.websecure.address=:443"
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

