apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-configs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rerichardjr/flux-av
    targetRevision: main
    path: infra-configs
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
