apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-appset-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rerichardjr/flux-av
    path: applicationsets
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
